### ISSUE TITLE
Invalid CSS selector in planet.css

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#117]
```css
/* Custom h1 to ensure major posts are separated */
h1c{
	font-size: 2em;
	margin: .67em 0;
	border-bottom: 15px solid var(--nav-font-color);
	display: inline-block;
	font-weight: 700;
	text-align: center;
}
```

`h1c` should probably be `h1`.  Someone might want to add an issue/pr to include [stylelint](https://stylelint.io/) like we have for eslint, to catch these types of bugs automatically.

cc @ODAVING, this came in with 0786e2cc it looks like.
