### ISSUE TITLE
Add a bot to automatically create PRs to update outdated dependencies

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#1647]
**What would you like to be added**:
Since we don't currently have a config file, Dependabot only seems to create PRs for security alerts. We should create a config file for Dependabot: https://github.com/Seneca-CDOT/telescope/network/updates or use an alternative bot to get automatically generated PRs for updating outdated dependencies.
**Why would you like this to be added**:
This would help us keep our dependencies up-to-date.

**Comment by humphd** [comment]
cc @yuanLeeMidori who is also interested in this.

**Comment by humphd** [comment]
https://github.com/renovatebot/renovate is another approach that we could run as a CI tool.

**Comment by birtony** [comment]
Based on our discussion with @yuanLeeMidori, we have identified the following requirements for the dependency bot that we are going to use:
- assigning reviewers - it would be helpful to configure the bot to set admin group as reviewers for each dependency update PR)
- commit message format - it would be helpful to be able to prefix commit messages generated by the bot in accordance with https://github.com/lob/generate-changelog#usage. For example, we could start each commit message with `type(chore): ` to something like that)
- scheduling (including time zone setting) - would be helpful to be able to configure how often and at what time the bot is going to check for outdated dependencies)

We have also identified the following features to be potentially useful:
- auto-merging dependency update PRs based on [semver ](https://github.com/npm/node-semver#functions) -  we _might_ want to merge all `patch` updates automatically when all checks pass)
- specifying labels to be assigned to dependency update PRs

**Comment by birtony** [comment]
I have looked into [Dependabot ](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) and identified the following:
- it does satisfy all three requirements identified above
- it does **not** allow us to automatically merge commits. However, this can be easily substituted with GitHub Actions. For example, [this action](https://github.com/marketplace/actions/dependabot-auto-merge) will tell Dependabot to merge dependency update PRs and Dependabot will do so after all checks successfully pass.
- it does support label configuration

For a full list of available configuration options, refer to https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

I have set up Dependabot in my forked repository and we can observe the results at https://github.com/birtony/telescope/pulls.
The configuration file can be as simple as the following:
```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
      time: '07:00'
      # Use Eastern Standard Time (UTC -05:00)
      timezone: 'America/Toronto'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'type(chore): '
    reviewers:
      - 'Seneca-CDOT/winter-2021-telescope'
```

However, we need to make sure that Dependabot checks for outdated dependencies in all of our `package.json` files. We might need to add more configurations to tell it to look specifically at our `src/frontend/gatsby`, `src/frontend/next` and `tools/autodeployment` folders for corresponding `package.json` files. That should also be easy to set up by just adding more rules to the config above.
