### ISSUE TITLE
Add Microservices docker-compose to production startup

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1706]
We currently deploy everything via [docker-compose-production.yml](https://github.com/Seneca-CDOT/telescope/blob/master/docker-compose-production.yml).  In this scenario, nginx is the gateway router to the rest of our apps.

We're going to add a second web host, where Traefik is the router to a bunch of Docker containers (our microservices, ELK stack apps, etc).

We're going to move to having two docker-compose files (and two versions of each):

```
/
  docker-compose.yml
  docker-compose-production.yml

  docker-compose-api.yml
  docker-compose-api-production.yml
```

The first set of files is for our current back-end and front-end run by nginx.  The second set (the `-api` ones) are for our Traefik based microservices.

In production, we are going to need to run them both, which means updating our deploy script(s) to use two docker-compose files:

```
docker-compose -f docker-compose-production.yml -f docker-compose-api-production.yml
```

In this way, "starting" Telescope would mean running the current app and also the new API web services at the same time, but on different hosts (#1704, #1705).

**Comment by humphd** [comment]
I started to experiment with this, and have a prototype working locally.  We need to figure out how to evolve our current setup to properly integrate the new docker-compose/env workflow for services with our existing system.

To start, I have a `docker-compose.yml` and `nginx.conf` that look like this (this is stripped down):

```
version: '3'

services:
  # API Gateway
  traefik:
    image: traefik:v2.4.5
    container_name: 'traefik'
    command:
      # If you need Traefik debug logs, uncomment this
      #- '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:8888'
    ports:
      - '8888:8888'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'

  # nginx as our main ingress point
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - traefik
    ports:
      - 80:80
```

And the nginx.conf:

```
  upstream api_gateway {
    server traefik:8888;
  }

  server {
    listen      80;
    server_name api.*;

    location / {
      proxy_pass          http://api_gateway;
      proxy_set_header    Host            $host;
      proxy_set_header    X-Real-IP       $remote_addr;
      proxy_set_header    X-Forwarded-for $remote_addr;
    }
  }

  server {
    listen      80 default_server;
    server_name telescope.localhost;

    location / {
      # Directory from which we serve Next's static content
      root /usr/share/nginx/html;
    }
  }
```

This has nginx watching the main web port (I use 80, but we'd do 80/443 in production).  I define an `upstream` server block for the traefik container running on port 8888 (I've modified the default port from 80/443, since nginx owns those).  If any requests come in to `api.*` we proxy that to Traefik.

I'm not sure how to deal with the naming differences between staging and production, so I've opted for the `api.*` prefix for now.

I'll see if I can do a PR to make this work in production, but wanted to share my notes.
