### ISSUE TITLE
Investigate Workflows in Circle CI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#281]
I got an email from Circle CI today, telling me about one of their features:

> Workflows allows you to define and orchestrate how the steps of job execution are run. 
>Use Workflows to:
- Use resources more efficiently 
- Increase speed by getting faster feedback
- Run and troubleshoot jobs independently with real-time status feedback
- Schedule jobs that should only run periodically
- Fan-out to run multiple jobs in parallel for efficient version testing
- Fan-in to quickly deploy to multiple platforms

See the [Workflow docs](https://circleci.com/docs/2.0/workflows/).

**Comment by humphd** [comment]
@RayGervais is thinking to give this a shot, which is awesome.  Second alumni to join the project! cc @SeanPrashad.

**Comment by raygervais** [comment]
Just some brainstorming to begin with after reviewing the documentation and general architecture of the application, defintialy open to more discussion and understanding the best approach in this case for CI/CD. 

*Notes*

- Allows parallel jobs, this could be advantagous for testing various components of telescope
- Daily deploys can be done via workflows, which enables master (post-CI/CD test passes) to always be displayed the most up to date since individual jobs can be run and green-lit prior to deployment. (This saves time and automates the deployment pattern).

*Potential Use-Cases*

- Acceptance and Integration Testing
The primary purpose of a workflow like this is to ensure that the application post-build complies with any acceptance, integration, and end-to-end testing prior to final deployment. Automated UI testing via Selenium for example could be a fantastic thing to always have running in the background.

```yml
workflows:
  version: 2
  build_accept_integration_end_deploy:
    jobs:
      - build
      - acceptance_test_1:
          requires:
            - build
      - integration:
          requires:
            - build
      - e2e_test:
          requires:
            - build
      - deploy:
          requires:
            - acceptance_test_1
            - integration
            - e2e_test
```

*Daily / Weekly Deployments*

The primary purpose of a workflow like this is to automate deployments and ensure latest features in master are deployed consistently.

```yml
workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - coverage
```
### (Architecture Dependant) Data Source Updates
In the case that we are pulling data and storing as templates or locally into the redis instance, a daily aggregate deployment may be a good way to ensure we always have the latest pulled and deployed per day.

Thoughts? I see in our package.json and CircleCI workspace that we are currently using `build` and `test` scripts right now.
