### ISSUE TITLE
Use docker.cdot.systems cached versions of Docker Hub Images

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3222]
Once https://github.com/Seneca-CDOT/docker.cdot.systems/issues/9 lands, we'll be able to pull Docker Hub images directly through docker.cdot.systems (i.e., it will cache them).

Let's switch our images for Traefik, nginx, Redis, Elasticsearch, etc. to use our own registry URL.

**Comment by TueeNguyen** [comment]
I Found this link https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy
I guess we can add something like this
```yml
nginx:
    image: docker.cdot.systems/redis
    pull_policy: missing

    build:
      context: ../src/web
      dockerfile: Dockerfile
      cache_from:
        - docker.cdot.systems/nginx:buildcache
      # next.js needs build-time access to a number of API URL values, forward as ARGs
      args:
```
